import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lumy/persistence/drift/local_database.dart';

import '../generated_migrations/schema.dart';

void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    // GeneratedHelper() was generated by drift, the verifier is an api
    // provided by drift_dev.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('Database', () {
    for (final version in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]) {
      test('upgrade from v$version to v${version + 1}', () async {
        final connection = await verifier.startAt(version);
        final db = LocalDatabase(connection);
        addTearDown(db.close);
        await verifier.migrateAndValidate(db, version + 1);
      });
    }
  });
}
